name: Deploy site

on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
        pnpm-version: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare pnpm ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: ${{matrix.pnpm-version}}
      - name: Prepare Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build static assets
        run: pnpm build
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy
          wranglerVersion: '4.95.0'
